# Generated by Django 4.1 on 2022-08-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform', '0003_alter_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseUser',
        ),
    ]
